### ISSUE TITLE
Chirp component sizes

### ISSUE THREAD

**Issue by KaruzG** [KaruzG/chirp#15]
![image](https://github.com/KaruzG/chirp/assets/95084763/6786f1f1-b5d1-4821-9c27-c10e60f0ae21)

The sizes of the chirp component should change, maybe relative ones or make it a parameter in the component. Something like:

max-width 100%; ---100% of parent element

Then whenever we import the component we control the size with the parent element using a container or smth. That way it adapts to every page.

**Comment by JME469** [comment]
You are right, I was testing with absolute sizes and forgot to change it. Should be fixed now. I have let the absolute min-width so the box don't get too thin, let me know how it works

**Comment by KaruzG** [comment]
Thanks!! ❤️
